### PR TITLE
added flashing tutorial and added kernel support for UBIFS

### PR DESCRIPTION
**Pull request by ddB0515**
Would you consider to add separate file for custom uBoot config same as for kernel
```
BR2_TARGET_UBOOT_USE_CUSTOM_CONFIG
BR2_TARGET_UBOOT_CUSTOM_CONFIG_FILE
```
so config file is separate from uBoot repo and can be modified
Also didn't find where is setup copying files for release (as tutorial is for `ubifs` rootfs) so would need to include it 

Anything else need let me know

### CODE REVIEW

**Comment by ddB0515** [comment]
@fifteenhex not sure if you have seen PR but can't add you as Reviewers :(

**Comment by fifteenhex** [comment]
I've seen it. I'll take a look when I get a bit of time.

**Comment by fifteenhex** [comment]
Hi @ddB0515 

Sorry for not getting back to you sooner.

Could you do me a favour: Split the "code" (uboot config stuff) into it's own patch and squash all of the text for your readme into a single commit?

**Comment by ddB0515** [comment]
No problem, will close this one and make new separate ones

**Pull request closed without merging**
